FROM python:3-alpine
RUN apk add --no-cache openssl-dev libffi-dev build-base
RUN pip install ansible boto3 awscli
RUN mkdir /code
WORKDIR /code
ENTRYPOINT [ "ansible-playbook", "-e", "ansible_connection=local", "-e", "ansible_python_interpreter=/usr/local/bin/python", "-i", "localhost,", "stack.yml" ]
